Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-04, with the labels that each got.

#58 Bug fix: failure to clean-up during CS Machine provisioning if VM provisioned to error state.
  config/rbac/role.yaml
  controllers/cloudstackmachine_controller.go
  main.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
Labels: approved, size/M, lgtm

#60 Fix/add listall list domains
  pkg/cloud/cluster.go
  pkg/cloud/cluster_test.go
  test/dummies/vars.go
Labels: approved, lgtm, size/L

#59 Remove IP assignment for CPs in a shared network
  pkg/cloud/instance.go
  templates/cluster-template-with-kube-vip.yaml
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-shared-network-kubevip/kustomization.yaml
  test/e2e/shared_network_kubevip.go
  test/e2e/shared_network_kubevip_test.go
Labels: approved, size/L

#61 Check the domain path always even if there is one domain returned.
  pkg/cloud/cluster.go
  pkg/cloud/cluster_test.go
  test/dummies/vars.go
Labels: approved, lgtm, size/L

#65 Use a local application spec using httpd image instead of a spec from internet
  test/e2e/data/fixture/expected-webpage.html
  test/e2e/data/fixture/sample-application.yaml
  test/e2e/deploy_app.go
Labels: approved, size/M, lgtm

#70 Adding support for deletion when a VM is detected as expunging
  pkg/cloud/client.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
Labels: approved, size/M, lgtm
