Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-05, with the labels that each got.

#74 Fix failed e2e tests
  pkg/cloud/cluster.go
  test/e2e/invalid_resource.go
Labels: approved, size/XS, lgtm, do-not-merge/hold

#71 Feature/implement machine health checker
  PROJECT
  api/v1beta1/cloudstackmachinestatechecker_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinestatecheckers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_cloudstackmachinestatecheckers.yaml
  config/crd/patches/webhook_in_cloudstackmachinestatecheckers.yaml
  config/rbac/cloudstackmachinestatechecker_editor_role.yaml
  config/rbac/cloudstackmachinestatechecker_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/infrastructure_v1beta1_cloudstackmachinestatechecker.yaml
  controllers/cloudstackaffinitygroup_controller.go
  controllers/cloudstackisolatednetwork_controller.go
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachinestatechecker_controller.go
  controllers/cloudstackzone_controller.go
  controllers/utils/base_reconciler.go
  main.go
Labels: approved, lgtm, size/L

#67 Add diskOffering to machine template config
  .gitignore
  api/v1beta1/cloudstackmachine_types.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  pkg/cloud/helpers.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  test/dummies/vars.go
Labels: approved, lgtm, size/L

#76 Subdomain User Operations
  controllers/cloudstackaffinitygroup_controller.go
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackisolatednetwork_controller.go
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackzone_controller.go
  controllers/utils/affinity_group.go
  controllers/utils/base_reconciler.go
  go.mod
  go.sum
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/cluster.go
  pkg/cloud/cluster_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/user_credentials.go
  pkg/cloud/user_credentials_test.go
Labels: approved, size/XL, /lgtm

#82 Release 0.4.3 artifacts
  releases/v0.4.3/EVALUATION_DEPLOYMENT.md
  releases/v0.4.3/RELEASE_NOTES.md
  releases/v0.4.3/clusterApi.zip
  releases/v0.4.3/security_findings.csv
  releases/v0.4.3/sha1sum.txt
Labels: approved, size/L

#83 Prepend Cluster Name to Zone and Iso Network CRs
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackzone_controller.go
  controllers/utils/affinity_group.go
  controllers/utils/isolated_network.go
  controllers/utils/zones.go
Labels: approved, size/S, /lgtm

#81 Add more linters and fix linter errors
  .golangci.yml
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinestatecheckers.yaml
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackisolatednetwork_controller.go
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackzone_controller.go
  controllers/utils/affinity_group.go
  controllers/utils/base_reconciler.go
  controllers/utils/isolated_network.go
  controllers/utils/utils.go
  controllers/utils/zones.go
  main.go
  pkg/cloud/client.go
  pkg/cloud/isolated_network.go
  pkg/cloud/tags.go
  pkg/cloud/user_credentials.go
  pkg/cloud/user_credentials_test.go
  test/dummies/vars.go
Labels: approved, lgtm, size/L

#77 Bumping ginkgo to v2 and adding code coverage check
  .github/workflows/go-coverage.yml
  Makefile
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/webhook_suite_test.go
  controllers/cloudstackcluster_controller_test.go
  controllers/controllers_suite_test.go
  go.mod
  go.sum
  hack/testing_ginkgo_recover_statements.sh
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client_test.go
  pkg/cloud/cloud_suite_test.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance_test.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/network_test.go
  pkg/cloud/tags_test.go
  pkg/cloud/user_credentials_test.go
  pkg/cloud/zone_test.go
Labels: approved, lgtm, size/L

#86 Get IsoNets by MetaName
  controllers/cloudstackzone_controller.go
Labels: approved, size/XS, lgtm

#90 Klogv2
  controllers/controllers_suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L

#91 v0.4.4 release artifacts
  ATTRIBUTION.txt
  releases/v0.4.4/EVALUATION_DEPLOYMENT.md
  releases/v0.4.4/RELEASE_NOTES.md
  releases/v0.4.4/clusterApi.zip
  releases/v0.4.4/security_findings.csv
  releases/v0.4.4/sha1sum.txt
Labels: approved, size/L

#92 Fix CloudStackMachine Missing Finalizer
  controllers/cloudstackmachine_controller.go
  controllers/utils/utils.go
Labels: approved, size/S

#93 Fix a bug where host affinity group is created when anti is specified
  controllers/cloudstackaffinitygroup_controller.go
Labels: approved, size/XS, lgtm

#94 Check VM instance ID is nil when deleting CS machine
  controllers/cloudstackmachine_controller.go
Labels: approved, size/XS, lgtm

#97 Fixup E2E Findings
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachinestatechecker_controller.go
  pkg/cloud/user_credentials.go
Labels: approved, size/S

#44 OWNERS: update per repo migration issue
  OWNERS
Labels: size/XS, lgtm, cncf-cla: yes, ok-to-test
