Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-07, with the labels that each got.

#122 Fix intermittent e2e deploy test failures where empty string returned as the test html
  test/e2e/common.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#134 Update to reflect new gcr.io repo
  Makefile
Labels: approved, lgtm, size/S, cncf-cla: yes

#124 Custom Metrics for ACS API calls.
  go.mod
  pkg/cloud/affinity_groups.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/instance.go
  pkg/cloud/isolated_network.go
  pkg/cloud/network.go
  pkg/cloud/tags.go
  pkg/cloud/user_credentials.go
  pkg/cloud/zone.go
  pkg/metrics/metrics.go
  test/e2e/common.go
  test/e2e/config/cloudstack.yaml
  test/e2e/deploy_app.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#132 Added e2e tests for upgrading clusters with insufficient compute resources
  test/e2e/common.go
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-insufficient-compute-resources-for-upgrade/kustomization.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-insufficient-compute-resources-for-upgrade/upgrade.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-insufficient-compute-resources/md.yaml
  test/e2e/invalid_resource.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#137 Added developer script for updating Amazon Route 53
  hack/update_route_53.sh
Labels: approved, lgtm, size/L, cncf-cla: yes

#138 Added alternative release-manifest with kube-rbac-proxy for exposing the metrics port.
  Makefile
  config/default-with-metrics-port/auth_proxy_client_clusterrole.yaml
  config/default-with-metrics-port/auth_proxy_role.yaml
  config/default-with-metrics-port/auth_proxy_role_binding.yaml
  config/default-with-metrics-port/auth_proxy_service.yaml
  config/default-with-metrics-port/kustomization.yaml
  config/default-with-metrics-port/manager_auth_proxy_patch.yaml
Labels: approved, size/M, lgtm, cncf-cla: yes
