Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-03, with the labels that each got.

#38 To match node names to machine names, use CAPI machine names when creating CloudStack VMs
  pkg/cloud/instance.go
Labels: approved, size/XS, lgtm

#39 Don't tag pre-existing networks or IP addresses
  pkg/cloud/network_test.go
  pkg/cloud/tags.go
  pkg/cloud/tags_test.go
Labels: approved, size/M, lgtm

#31 feature/failure domains
  .gitignore
  Makefile
  api/v1beta1/cloudstackcluster_types.go
  api/v1beta1/cloudstackcluster_webhook.go
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachine_types.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/webhook_suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  config/dev/kustomization.yaml
  config/develop/insecure_manager.yaml
  config/develop/kustomization.yaml
  config/develop/manager_open_debug_port.yaml
  config/manager/kustomization.yaml
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackcluster_controller_test.go
  controllers/cloudstackmachine_controller.go
  hack/add_addresses.sh
  hack/nginx.conf
  hack/setup_for_dev.sh
  main.go
  pkg/cloud/affinity_groups.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/client_test.go
  pkg/cloud/cluster.go
  pkg/cloud/cluster_test.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/cloud/tags.go
  pkg/cloud/tags_test.go
  templates/cluster-template-managed-ssh.yaml
  templates/cluster-template-ssh-material.yaml
  templates/cluster-template.yaml
  test/dummies/vars.go
  tilt-provider.json
Labels: approved, size/XXL

#41 Change template and offering to explicitly specify ID or Name
  .gitignore
  api/v1beta1/cloudstackmachine_types.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/webhookutil/webhook_validators.go
  test/dummies/vars.go
Labels: approved, size/XL

#42 Fixup/load balance get or create
  controllers/cloudstackmachine_controller.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  test/dummies/vars.go
Labels: approved, size/M, lgtm

#43 Changed to match API.
  templates/cluster-template-managed-ssh.yaml
  templates/cluster-template-ssh-material.yaml
  templates/cluster-template.yaml
Labels: approved, size/M

#40 New v0.4.0 Release Notes and Evaluation Deployment files.
  ATTRIBUTION.txt
  releases/v0.4.0/EVALUATION_DEPLOYMENT.md
  releases/v0.4.0/RELEASE_NOTES.md
  releases/v0.4.0/clusterApi.zip
  releases/v0.4.0/security_findings.csv
  releases/v0.4.0/sha1sum.txt
Labels: approved, size/XL

#47 Call openFirewallRules in CreateIsolatedNetwork to create an egress rule
  pkg/cloud/network.go
  pkg/cloud/network_test.go
Labels: approved, lgtm, size/S

#45 E2e 2 clusters
  test/e2e/README.md
  test/e2e/common.go
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-second-cluster/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-second-cluster/kustomization.yaml
  test/e2e/two_clusters.go
  test/e2e/two_clusters_test.go
Labels: approved, lgtm, size/L

#48 Fix misspells
  controllers/utils/utils.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
Labels: approved, size/XS

#50 Fix a bug in ZoneStatusMap.GetByName
  api/v1beta1/cloudstackcluster_types.go
  api/v1beta1/cloudstackcluster_types_test.go
Labels: approved, size/M

#51 ETCD Catch NPE and ETCD Owner
  controllers/utils/utils.go
Labels: approved, lgtm, size/S

#53 Release v0.4.1 artifacts
  releases/v0.4.1/EVALUATION_DEPLOYMENT.md
  releases/v0.4.1/RELEASE_NOTES.md
  releases/v0.4.1/clusterApi.zip
  releases/v0.4.1/security_findings.csv
  releases/v0.4.1/sha1sum.txt
Labels: approved, size/L
