Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-09, with the labels that each got.

#159 makefile: Add cluster-templates to release-staging
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes

#158 Ported templates to v1beta2
  templates/cluster-template-managed-ssh.yaml
  templates/cluster-template-ssh-material.yaml
  templates/cluster-template-with-disk-offering.yaml
  templates/cluster-template-with-kube-vip.yaml
  templates/cluster-template.yaml
Labels: approved, size/L, cncf-cla: yes

#157 Revised doc files for V0.4.7
  docs/book/src/clustercloudstack/configuration.md
  docs/book/src/development/common.md
  docs/book/src/getting-started.md
Labels: approved, size/L, cncf-cla: yes

#162 Revert "api: Allow changes to CloudstackMachineTemplate"
  api/v1beta2/cloudstackmachinetemplate_webhook.go
  api/v1beta2/cloudstackmachinetemplate_webhook_test.go
Labels: approved, size/M, cncf-cla: yes

#167 export hack/tools/bin folder to PATH
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes
