Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-06, with the labels that each got.

#105 Merging repo changes made during migration
  Makefile
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#112 Update netlify.toml for website
  netlify.toml
Labels: approved, lgtm, size/S, cncf-cla: yes

#106 Renaming project to use new project path
  PROJECT
  api/v1beta1/cloudstackcluster_webhook.go
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/webhook_suite_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  controllers/cloudstackaffinitygroup_controller.go
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackcluster_controller_test.go
  controllers/cloudstackisolatednetwork_controller.go
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachinestatechecker_controller.go
  controllers/cloudstackzone_controller.go
  controllers/controllers_suite_test.go
  controllers/utils/affinity_group.go
  controllers/utils/base_reconciler.go
  controllers/utils/isolated_network.go
  controllers/utils/zones.go
  go.mod
  main.go
  pkg/cloud/affinity_groups.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/isolated_network.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/cloud/tags.go
  pkg/cloud/tags_test.go
  pkg/cloud/user_credentials_test.go
  pkg/cloud/zone.go
  pkg/cloud/zone_test.go
  test/dummies/vars.go
  test/e2e/go.mod
Labels: approved, lgtm, size/L, cncf-cla: yes

#110 Readding self as approver for CAPC repo
  OWNERS
Labels: approved, size/XS, lgtm, cncf-cla: yes

#114 Adding maxdrib to readme as reviewer/maintainer
  README.md
Labels: approved, size/XS, lgtm, cncf-cla: yes

#116 Update docs and fix broken links
  README.md
  docs/book/src/clustercloudstack/configuration.md
  docs/book/src/development/building.md
  docs/book/src/development/index.md
  docs/book/src/development/tilt.md
  docs/book/src/getting-started.md
  docs/book/src/topics/custom-images.md
Labels: approved, size/M, cncf-cla: yes

#118 Add rejoshed as owner/maintainer.
  OWNERS
  README.md
Labels: approved, size/XS, lgtm, cncf-cla: yes

#126 Fixup for Zones Panic
  controllers/cloudstackmachine_controller.go
  controllers/utils/zones.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#121 Tests/Account & Domain Isolation and More Domain/Account Tests
  .golangci.yml
  Makefile
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/webhook_suite_test.go
  controllers/controllers_suite_test.go
  go.mod
  go.sum
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/cloud_suite_test.go
  pkg/cloud/helpers_test.go
  pkg/cloud/isolated_network.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/tags_test.go
  pkg/cloud/user_credentials_test.go
  pkg/cloud/zone_test.go
  test/dummies/vars.go
  test/fixtures/cloud-config-files/cloud-config-good
  test/fixtures/cloud-config-files/cloud-config-no-global
  test/helpers/client.go
  test/helpers/suite_test.go
  test/helpers/user.go
  test/helpers/user_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#128 Issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/M, lgtm, cncf-cla: yes

#129 GetZonesAndRequeueIfMissing method added to fix affinity group deletion
  controllers/cloudstackmachine_controller.go
  controllers/utils/zones.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#131 Add jweite-amazon as an OWNER
  OWNERS
Labels: approved, size/XS, lgtm, cncf-cla: yes

#130 Remove stopping machine from DestroyOneMachine
  test/e2e/common.go
Labels: approved, size/XS, lgtm, cncf-cla: yes
