Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-01, with the labels that each got.

#7 Fix/tilt fixup
  Makefile
  README.md
  config/insecure_manager.yaml
  config/kustomization.yaml
  tilt-provider.json
Labels: approved, lgtm, size/S

#9 Compress user_data using gzip to avoid to exceed the hard limit (32KB)
  controllers/cloudstackmachine_controller.go
  pkg/cloud/helpers.go
Labels: approved, lgtm, size/S

#11 Revert "Compress user_data using gzip to avoid to exceed the hard limit (32KB)"
  controllers/cloudstackmachine_controller.go
  pkg/cloud/helpers.go
Labels: approved, size/S

#10 Adding cluster webhook validation for control plane endpoint
  api/v1alpha3/cloudstackcluster_webhook.go
  api/v1alpha3/cloudstackcluster_webhook_test.go
Labels: approved, lgtm, size/S

#13 Updating repo to support v0.3 output artifacts
  Makefile
  metadata.yaml
Labels: approved, size/XS, lgtm

#15 Refactoring account/domain validation webhook logic
  api/v1alpha3/cloudstackcluster_webhook.go
Labels: approved, size/XS, lgtm

#16 v0.3.0 release notes
  releases/ATTRIBUTION.txt
  releases/v0.3.0/RELEASE_NOTES.md
Labels: approved, lgtm, size/XXL

#17 attribution file clean up
  ATTRIBUTION.txt
  releases/ATTRIBUTION.txt
Labels: approved, lgtm, size/XXL

#18 Added Remaining v0.3.0 release files.
  releases/v0.3.0/EVALUATION_DEPLOYMENT.md
  releases/v0.3.0/clusterApi.zip
  releases/v0.3.0/security_findings.csv
  releases/v0.3.0/sha1sum.txt
Labels: approved, lgtm, size/L

#19 Feature/health check v ms
  templates/controlPlaneMachineHealthCheck.yaml
  templates/workerMachineHealthCheck.yaml
Labels: approved, size/M, lgtm

#21 Bump timeout.
  controllers/cloudstackcluster_controller_test.go
Labels: approved, size/XS, lgtm

#20 Feature/v1beta1
  Makefile
  api/v1beta1/cloudstackcluster_types.go
  api/v1beta1/cloudstackcluster_webhook.go
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachine_types.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_types.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/conversion.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/webhook_suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/kustomizeconfig.yaml
  config/default/webhookcainjection_patch.yaml
  config/dev/insecure_manager.yaml
  config/dev/kustomization.yaml
  config/webhook/manifests.yaml
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackcluster_controller_test.go
  controllers/cloudstackmachine_controller.go
  controllers/controllers_suite_test.go
  go.mod
  go.sum
  main.go
  metadata.yaml
  pkg/cloud/client.go
  pkg/cloud/cluster.go
  pkg/cloud/cluster_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/mocks/mock_client.go
  tilt-provider.json
Labels: approved, lgtm, size/XXL
