Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-12, with the labels that each got.

#198 add events to cloudstack machine resource
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachine_controller_test.go
  controllers/controllers_suite_test.go
  controllers/utils/base_reconciler.go
  main.go
Labels: approved, size/L, needs-ok-to-test, cncf-cla: yes

#192 Explicitly adding links for prebuilt images
  README.md
Labels: approved, size/M, lgtm, cncf-cla: yes

#201 Add finalizer only when deployVM no error
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachine_controller_test.go
  pkg/cloud/instance.go
Labels: approved, lgtm, size/S, cncf-cla: yes, ok-to-test

#141 e2e: Add kubernetes version upgrade test
  test/e2e/common.go
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-after/cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-after/kustomization.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-after/upgrade-cp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-after/upgrade-md.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-before/before.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-before/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-before/kustomization.yaml
  test/e2e/kubernetes_version_upgrade.go
  test/e2e/kubernetes_version_upgrade_test.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#203 tests: Fix error for when a VM is unable to deploy
  test/e2e/invalid_resource.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#204 Removed maxdrib - he's departed the team.
  OWNERS
  README.md
Labels: size/XS, lgtm, needs-ok-to-test, cncf-cla: yes

#193 First draft of Toxiproxy-based network interruption E2E test.
  Makefile
  test/e2e/deploy_app_toxi.go
  test/e2e/e2e_suite_test.go
  test/e2e/helpers/utilities.go
  test/e2e/kubeconfig_helper/data/README
  test/e2e/kubeconfig_helper/data/kubeconfig
  test/e2e/kubeconfig_helper/kubeconfig.go
  test/e2e/kubeconfig_helper/kubeconfig_test.go
  test/e2e/kubeconfig_helper/suite_test.go
  test/e2e/network_interruption_toxi.go
  test/e2e/network_interruption_toxi_test.go
  test/e2e/toxiproxy/toxiProxy.go
Labels: approved, size/L, cncf-cla: yes
