Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-02, with the labels that each got.

#8 Feature/affinity management
  Makefile
  PROJECT
  README.md
  api/v1beta1/cloudstackcluster_webhook.go
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachine_types.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  config/rbac/role.yaml
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackcluster_controller_test.go
  controllers/cloudstackmachine_controller.go
  controllers/utils/utils.go
  main.go
  metadata.yaml
  pkg/cloud/affinity_groups.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/cluster.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
  pkg/mocks/mock_client.go
  templates/cluster-template-managed-ssh.yaml
  templates/cluster-template-ssh-material.yaml
  templates/cluster-template.yaml
  templates/controlPlaneMachineHealthCheck.yaml
  templates/workerMachineHealthCheck.yaml
Labels: approved, lgtm, size/XXL

#25 Minor code cleanup
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
Labels: approved, lgtm, size/L

#22 Exposing controller metrics on port 8080 on all IPs, a la CAPV.
  config/default/kustomization.yaml
  config/default/manager_prometheus_metrics_patch.yaml
Labels: approved, lgtm, size/S

#30 Feature/ssl opt
  .gitignore
  Makefile
  pkg/cloud/client.go
  pkg/cloud/client_test.go
  pkg/cloud/helpers_test.go
  pkg/mocks/.keep
  pkg/mocks/mock_client.go
Labels: approved, lgtm, size/L

#28 feature/tag-network
  api/v1beta1/cloudstackcluster_webhook_test.go
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackcluster_controller_test.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/cluster.go
  pkg/cloud/cluster_test.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/cloud/tags.go
  pkg/cloud/tags_test.go
Labels: approved, size/L

#32 Repo prep per guidance from - https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories
  .golangci.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  NOTICE
  README.md
  SECURITY_CONTACTS
  api/v1beta1/cloudstackcluster_types.go
  api/v1beta1/cloudstackcluster_webhook.go
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachine_types.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachine_webhook_test.go
  api/v1beta1/cloudstackmachinetemplate_types.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook_test.go
  api/v1beta1/conversion.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/webhook_suite_test.go
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackcluster_controller_test.go
  controllers/cloudstackmachine_controller.go
  controllers/controllers_suite_test.go
  controllers/utils/utils.go
  main.go
  pkg/cloud/affinity_groups.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/client_test.go
  pkg/cloud/cloud_suite_test.go
  pkg/cloud/cluster.go
  pkg/cloud/cluster_test.go
  pkg/cloud/helpers.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/webhook_utilities/webhook_validators.go
Labels: do-not-merge/work-in-progress, approved, size/L

#33 Fix/add golint fix lint errors
  .golangci.yml
  Makefile
  api/v1beta1/cloudstackcluster_webhook.go
  api/v1beta1/cloudstackcluster_webhook_test.go
  api/v1beta1/cloudstackmachine_webhook.go
  api/v1beta1/cloudstackmachinetemplate_webhook.go
  api/v1beta1/groupversion_info.go
  config/webhook/manifests.yaml
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackmachine_controller.go
  controllers/utils/utils.go
  main.go
  pkg/cloud/affinity_groups.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/client_test.go
  pkg/cloud/cluster.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/cloud/tags.go
  pkg/cloud/tags_test.go
  pkg/webhookutil/webhook_validators.go
Labels: approved, lgtm, size/L

#36 escape the $ in make file
  Makefile
Labels: approved, size/XS, lgtm

#37 Destroy VM asynchronously
  controllers/cloudstackmachine_controller.go
  pkg/cloud/client.go
  pkg/cloud/instance.go
Labels: approved, size/M, lgtm

#35 Tagging and cleaning up IP addresses
  README.md
  pkg/cloud/affinity_groups.go
  pkg/cloud/cluster.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/cloud/tags.go
  pkg/cloud/tags_test.go
Labels: approved, size/L
