Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-10, with the labels that each got.

#168 Remove checking name when looking for a certain error message because…
  test/e2e/invalid_resource.go
Labels: size/XS, lgtm, cncf-cla: yes

#165 E2e toxiproxy
  .gitignore
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackaffinitygroups.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackfailuredomains.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackisolatednetworks.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinestatecheckers.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackzones.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  controllers/utils/affinity_group.go
  go.mod
  test/e2e/README.md
  test/e2e/deploy_app_toxi.go
  test/e2e/deploy_app_toxi_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/helpers/data/README
  test/e2e/helpers/data/kubeconfig
  test/e2e/helpers/kubeconfig.go
  test/e2e/helpers/kubeconfig_test.go
  test/e2e/helpers/suite_test.go
  test/e2e/helpers/toxiProxy.go
Labels: approved, lgtm, size/XL, cncf-cla: yes

#173 Added least privilege role description to docs (book).
  docs/book/src/SUMMARY.md
  docs/book/src/topics/cloudstack-permissions.md
  docs/book/src/topics/index.md
Labels: approved, size/M, cncf-cla: yes

#164 Failuredomain deletion
  Makefile
  api/v1beta2/zz_generated.deepcopy.go
  config/rbac/role.yaml
  controllers/cloudstackcluster_controller_test.go
  controllers/cloudstackfailuredomain_controller.go
  controllers/cloudstackfailuredomain_controller_test.go
  controllers/controllers_suite_test.go
  go.mod
  test/dummies/v1beta2/vars.go
  test/fakes/CloudStackMachineOwner_types.go
  test/fakes/fakes.infrastructure.cluster.x-k8s.io_cloudstackmachineowners.yaml
  test/fakes/groupversion_info.go
  test/fakes/zz_generated.deepcopy.go
Labels: size/XXL, needs-ok-to-test, cncf-cla: yes

#170 Use capi machine name as hostname and k8s node name
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachine_controller_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  test/dummies/v1beta2/vars.go
Labels: approved, size/M, lgtm, needs-ok-to-test, cncf-cla: yes

#176 Making ObjectMeta in CloudStackMachineTemplateResource nullable
  api/v1beta2/cloudstackmachinetemplate_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
Labels: approved, size/XS, cncf-cla: yes

#177 Fixing Makefile bugs
  Makefile
  common.mk
  docs/book/Makefile
  hack/tools/Makefile
Labels: approved, size/S, cncf-cla: yes

#179 Fixing broken build on linux due to inline comment
  common.mk
Labels: approved, size/XS, cncf-cla: yes

#181 update regexp for ds.meta_data.failuredomain replacement
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachine_controller_test.go
  test/dummies/v1beta2/vars.go
Labels: approved, size/S, needs-ok-to-test, cncf-cla: yes

#180 Update failuredomain regexp and prevent race condition while removing failure domain
  controllers/cloudstackfailuredomain_controller.go
  controllers/cloudstackfailuredomain_controller_test.go
  controllers/cloudstackmachine_controller.go
  go.mod
Labels: approved, size/L, needs-ok-to-test, cncf-cla: yes

#182 Fixed faulty command path in run-e2e target, caused by another recent…
  Makefile
Labels: approved, size/XS, cncf-cla: yes

#183 Release v0.4.8 artifacts
  Makefile
  releases/v0.4.8/RELEASE_NOTES.md
  releases/v0.4.8/security_findings.csv
Labels: approved, size/M, cncf-cla: yes

#184 Removed rejosh from OWNERS - he's left the team.
  OWNERS
  README.md
Labels: approved, size/XS, cncf-cla: yes

#185 Fix Makefile to run e2e
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes
