Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2022-08, with the labels that each got.

#146 Disabling machine state checker
  main.go
Labels: size/XS, lgtm, cncf-cla: yes

#147 Feature/hash failure domain naming
  .gitignore
  Makefile
  api/v1beta1/zz_generated.conversion.go
  api/v1beta2/cloudstackfailuredomain_types.go
  api/v1beta2/cloudstackisolatednetwork_types.go
  api/v1beta2/cloudstackmachine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackfailuredomains.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackisolatednetworks.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  controllers/cloudstackaffinitygroup_controller.go
  controllers/cloudstackaffinitygroup_controller_test.go
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackfailuredomain_controller.go
  controllers/cloudstackisolatednetwork_controller.go
  controllers/cloudstackmachine_controller.go
  controllers/cloudstackmachine_controller_test.go
  controllers/cloudstackmachinestatechecker_controller.go
  controllers/utils/failuredomains.go
  controllers/utils/isolated_network.go
  test/dummies/v1beta2/vars.go
  test/e2e/data/infrastructure-cloudstack/v1beta2/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-affinity-group-anti.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-affinity-group-pro.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-custom-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-insufficient-compute-resources-for-upgrade.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-insufficient-compute-resources.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-account.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-account/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-cp-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-disk-offering-size-for-customized.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-disk-offering-size-for-non-customized.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-domain.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-domain/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-template.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-zone.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-zone/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-machine-remediation.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-node-drain.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-resource-cleanup.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-resource-cleanup/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-second-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-second-cluster/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-shared-network-kubevip.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-subdomain.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-subdomain/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template.yaml
Labels: approved, size/XXL, cncf-cla: yes

#148 Addressing bug where account/domain was lost
  api/v1beta1/conversion.go
  api/v1beta1/conversion_test.go
Labels: approved, size/M, cncf-cla: yes

#152 Bugfix clearmachine
  controllers/cloudstackmachine_controller.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, cncf-cla: yes

#151 customize v1beta1 affinity group conversion to v1beta2
  api/v1beta1/cloudstackaffinitygroup_conversion.go
  api/v1beta1/cloudstackaffinitygroup_types.go
  api/v1beta1/conversion_test.go
  api/v1beta1/zz_generated.conversion.go
  config/crd/kustomization.yaml
Labels: size/L, needs-ok-to-test, cncf-cla: yes

#136 Standardizing makefile and adding automated builds
  Makefile
  common.mk
  controllers/controllers_suite_test.go
  hack/setup_for_dev.sh
  hack/testing_ginkgo_recover_statements.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/cloud/client.go
  pkg/cloud/client_test.go
  pkg/cloud/cloud_suite_test.go
  test/dummies/v1beta1/vars.go
  test/dummies/v1beta2/vars.go
  test/helpers/client.go
Labels: approved, size/XXL, cncf-cla: yes

#139 [tests] Extend unit tests for cloud package
  api/v1beta1/conversion_test.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client_test.go
  pkg/cloud/isolated_network.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/cloud/tags_test.go
  pkg/cloud/user_credentials_test.go
  pkg/cloud/zone_test.go
  test/dummies/v1beta1/vars.go
  test/dummies/v1beta2/vars.go
Labels: approved, lgtm, size/XXL, cncf-cla: yes

#140 e2e: Add test for invalid ip as control plane endpoint
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-ip/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-invalid-ip/kustomization.yaml
  test/e2e/invalid_resource.go
Labels: approved, size/M, lgtm, cncf-cla: yes
