Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2023-06, with the labels that each got.

#261 Makefile/e2e: ensure cloud-config.yaml exists
  Makefile
  hack/ensure-cloud-config-yaml.sh
Labels: approved, size/M, lgtm, cncf-cla: yes

#262 Added cni plugin
  docs/book/src/development/common.md
Labels: approved, size/M, lgtm, cncf-cla: yes, ok-to-test

#235 Open egress firewall for UDP and ICMP too
  docs/book/src/clustercloudstack/configuration.md
  pkg/cloud/isolated_network.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/network.go
Labels: approved, size/M, lgtm, cncf-cla: yes, ok-to-test

#267 e2e: restore secret name to original while running tests with ToxiProxy
  test/e2e/toxiproxy/toxiProxy.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#269 Makefile: Fix release-templates
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes

#273 Sync main changes to v1beta3
  Makefile
  OWNERS
  api/v1beta2/cloudstackmachine_types.go
  api/v1beta2/cloudstackmachine_types_test.go
  docs/book/src/clustercloudstack/configuration.md
  docs/book/src/development/common.md
  go.mod
  go.sum
  hack/ensure-cloud-config-yaml.sh
  hack/ensure-kind.sh
  pkg/cloud/helpers.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/isolated_network.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/network.go
  pkg/cloud/user_credentials.go
  test/e2e/common.go
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-custom-disk-offering/cluster-with-custom-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-disk-offering/cluster-with-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-custom-disk-offering/cluster-with-custom-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-disk-offering/cluster-with-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-after/upgrade-cp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-before/before.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/toxiproxy/toxiProxy.go
Labels: approved, lgtm, size/XL, needs-ok-to-test, cncf-cla: yes

#276 e2e: Decrease network interruption time for toxiproxy test
  test/e2e/network_interruption_toxi.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, cncf-cla: yes

#278 docs: add username when access nodes via ssh
  docs/book/src/topics/ssh-access.md
Labels: approved, size/XS, lgtm, cncf-cla: yes

#283 Remove golangci-lint installation script
  hack/ensure-golangci-lint.sh
  hack/tools/Makefile
Labels: approved, lgtm, size/L, cncf-cla: yes
