Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2023-07, with the labels that each got.

#286 Fix affinity group naming
  controllers/cloudstackmachine_controller.go
  controllers/utils/affinity_group.go
  controllers/utils/utils.go
Labels: approved, size/M, lgtm, cncf-cla: yes, ok-to-test

#284 Check available limits before deploying a VM
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/client_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/network_test.go
  pkg/cloud/tags_test.go
  pkg/cloud/user_credentials.go
  pkg/cloud/user_credentials_test.go
  pkg/cloud/zone_test.go
  test/e2e/invalid_resource.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test

#288 Remove v1beta1 webhook test suite
  api/v1beta1/webhook_suite_test.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#294 Remove shared network IP availability check
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
Labels: approved, lgtm, size/L, cncf-cla: yes

#291 Rework the Makefile to separate tilt commands
  Makefile
Labels: approved, lgtm, size/S, cncf-cla: yes

#281 Add checks to ensure that ReconcileDelete runs
  controllers/cloudstackmachine_controller.go
  controllers/utils/base_reconciler.go
Labels: approved, lgtm, size/S, cncf-cla: yes, ok-to-test

#296 Concurrently reconcile CloudStackCluster resources
  config/manager/manager.yaml
  controllers/cloudstackcluster_controller.go
  controllers/cloudstackcluster_controller_test.go
  main.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#300 Upgrade CAPI clone verison used in Tilt
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes
