Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2023-03, with the labels that each got.

#223 Add g-gaston to OWNERS
  OWNERS
Labels: approved, size/XS, lgtm, cncf-cla: yes

#216 Add flag to allow userdata to be uncompressed
  api/v1beta2/cloudstackmachine_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackmachinetemplates.yaml
  pkg/cloud/helpers.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
Labels: size/M, lgtm, cncf-cla: yes, ok-to-test

#224 Replace k8s.gcr.io with registry.k8s.io
  Makefile
  docs/book/src/topics/unstacked-etcd.md
  test/e2e/data/infrastructure-cloudstack/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-custom-disk-offering/cluster-with-custom-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-disk-offering/cluster-with-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-custom-disk-offering/cluster-with-custom-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-disk-offering/cluster-with-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-after/upgrade-cp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-before/before.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes

#226 Download golangci-lint instead of building it
  hack/ensure-golangci-lint.sh
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: lgtm, size/XXL, needs-ok-to-test, cncf-cla: yes
