Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2023-05, with the labels that each got.

#232 Add tolerations to capc-controller-manager
  config/manager/manager.yaml
Labels: approved, size/XS, lgtm, cncf-cla: yes, ok-to-test

#236 Fix tilt's debug configuration
  docs/book/src/development/tilt.md
Labels: approved, size/XS, lgtm, needs-ok-to-test, cncf-cla: yes

#238 Makefile: fix 'make tilt-up'
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes, ok-to-test

#234 Tidy API objects and simplify webhook validation util
  api/v1beta2/cloudstackaffinitygroup_types.go
  api/v1beta2/cloudstackcluster_types.go
  api/v1beta2/cloudstackcluster_webhook.go
  api/v1beta2/cloudstackfailuredomain_types.go
  api/v1beta2/cloudstackisolatednetwork_types.go
  api/v1beta2/cloudstackmachine_types.go
  api/v1beta2/cloudstackmachine_webhook.go
  api/v1beta2/cloudstackmachinestatechecker_types.go
  api/v1beta2/cloudstackmachinetemplate_types.go
  api/v1beta2/cloudstackmachinetemplate_webhook.go
  pkg/webhookutil/webhook_validators.go
Labels: approved, lgtm, size/L, cncf-cla: yes, ok-to-test

#230 Upgrade cluster-api dependency to v1.2.12
  Makefile
  go.mod
  go.sum
  test/e2e/config/cloudstack.yaml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, size/M, lgtm, cncf-cla: yes, ok-to-test

#243 e2e: set imageRepository to "" in yaml files
  test/e2e/data/infrastructure-cloudstack/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-custom-disk-offering/cluster-with-custom-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-disk-offering/cluster-with-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta1/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-custom-disk-offering/cluster-with-custom-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-disk-offering/cluster-with-disk-offering.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-after/upgrade-cp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-kubernetes-version-upgrade-before/before.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta2/cluster-template-shared-network-kubevip/cluster-with-shared-network-and-kubevip.yaml
Labels: approved, lgtm, size/S, cncf-cla: yes, ok-to-test

#242 e2e: fix "Failed to compile e2e"
  go.mod
  go.sum
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, lgtm, size/S, cncf-cla: yes, ok-to-test

#257 e2e: fix two_clusters.go if there are multiple users under ROOT/admin
  pkg/cloud/user_credentials.go
Labels: approved, size/XS, lgtm, cncf-cla: yes, ok-to-test

#247 e2e: fix disk_offering_test.go
  test/e2e/common.go
Labels: approved, lgtm, size/S, cncf-cla: yes, ok-to-test

#254 Fix userdata compression
  Makefile
  api/v1beta2/cloudstackmachine_types.go
  api/v1beta2/cloudstackmachine_types_test.go
  pkg/cloud/helpers.go
  pkg/cloud/helpers_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
Labels: approved, lgtm, size/L, cncf-cla: yes, ok-to-test

#259 Makefile: add run-e2e-smoke
  Makefile
Labels: approved, size/XS, lgtm, cncf-cla: yes

#260 Makefile: ensure kind before running e2e smoke test
  Makefile
  hack/ensure-kind.sh
Labels: approved, size/M, lgtm, cncf-cla: yes
