Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2024-05, with the labels that each got.

#329 Fix CRD contract version label
  config/crd/kustomization.yaml
Labels: approved, size/XS, lgtm, cncf-cla: yes, ok-to-test

#338 Update ttlcache library to v3, disable TTL extension on hit
  go.mod
  go.sum
  pkg/cloud/client.go
Labels: approved, size/M, lgtm, cncf-cla: yes, ok-to-test, release:must-have

#358 Fixup unit test failures
  controllers/cloudstackaffinitygroup_controller_test.go
Labels: approved, lgtm, size/S, cncf-cla: yes, ok-to-test

#356 Add project support
  api/v1beta1/conversion.go
  api/v1beta3/cloudstackfailuredomain_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackfailuredomains.yaml
  controllers/cloudstackaffinitygroup_controller_test.go
  controllers/utils/failuredomains.go
  pkg/cloud/affinity_groups.go
  pkg/cloud/affinity_groups_test.go
  pkg/cloud/client.go
  pkg/cloud/client_test.go
  pkg/cloud/cloud_suite_test.go
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/isolated_network.go
  pkg/cloud/isolated_network_test.go
  pkg/cloud/network.go
  pkg/cloud/network_test.go
  pkg/cloud/tags.go
  pkg/cloud/user_credentials.go
  pkg/cloud/user_credentials_test.go
  pkg/cloud/zone.go
  pkg/cloud/zone_test.go
  test/e2e/common.go
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta3/cluster-template-project/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta3/cluster-template-project/kustomization.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta3/cluster-template-project/md.yaml
  test/e2e/project.go
  test/e2e/project_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test, release:must-have

#360 Fixup make generate-conversion
  api/v1beta2/cloudstackfailuredomain_conversion.go
  api/v1beta2/zz_generated.conversion.go
Labels: approved, size/M, lgtm, cncf-cla: yes
