Repository kubernetes-sigs/cluster-api-provider-cloudstack, pull requests merged in 2024-06, with the labels that each got.

#361 Fix naming of isolated network if the network name contains an underscore
  controllers/utils/isolated_network.go
Labels: approved, size/XS, lgtm, cncf-cla: yes

#357 Allow cluster creation by a normal ACS user
  docs/book/src/topics/cloudstack-permissions.md
  pkg/cloud/instance.go
  pkg/cloud/instance_test.go
  pkg/cloud/user_credentials.go
Labels: approved, size/M, lgtm, cncf-cla: yes, ok-to-test, release:must-have

#308 Tilt metrics fix + docs update
  config/default/kustomization.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/manager/manager.yaml
  docs/book/src/development/tilt.md
  test/e2e/config/cloudstack.yaml
Labels: approved, size/M, lgtm, cncf-cla: yes, ok-to-test

#363 Add dependabot automation
  .github/dependabot.yaml
Labels: approved, size/M, lgtm, cncf-cla: yes

#374 Change go version to 1.21
  .github/workflows/go-coverage.yml
  Makefile
  controllers/cloudstackmachine_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  main.go
  netlify.toml
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, size/M, lgtm, cncf-cla: yes

#350 Reconcile CAPC Cluster as CloudStack CKS Cluster (Default: Opt Out)
  api/v1beta1/conversion.go
  api/v1beta2/cloudstackcluster_conversion.go
  api/v1beta2/zz_generated.conversion.go
  api/v1beta3/cloudstackcluster_types.go
  api/v1beta3/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_cloudstackclusters.yaml
  config/manager/manager.yaml
  controllers/cks_cluster_controller.go
  controllers/cks_cluster_controller_test.go
  controllers/cks_machine_controller.go
  controllers/cks_machine_controller_test.go
  controllers/cloudstackfailuredomain_controller.go
  controllers/controllers_suite_test.go
  docs/book/src/development/common.md
  docs/book/src/getting-started.md
  main.go
  pkg/cloud/cks_cluster.go
  pkg/cloud/client.go
  templates/cluster-template-managed-ssh.yaml
  templates/cluster-template-ssh-material.yaml
  templates/cluster-template-with-disk-offering.yaml
  templates/cluster-template-with-kube-vip.yaml
  templates/cluster-template.yaml
  test/dummies/v1beta3/vars.go
  test/e2e/common.go
  test/e2e/config/cloudstack.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta3/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta3/cluster-template-k8s-cks/cloudstack-cluster.yaml
  test/e2e/data/infrastructure-cloudstack/v1beta3/cluster-template-k8s-cks/kustomization.yaml
  test/e2e/go.mod
  test/e2e/go.sum
  test/e2e/kubernetes_cks_cluster.go
  test/e2e/kubernetes_cks_cluster_test.go
Labels: approved, lgtm, size/XL, cncf-cla: yes, ok-to-test, release:must-have

#383 test/e2e: Update ginkgo version for test/e2e
  test/e2e/go.mod
  test/e2e/go.sum
Labels: approved, size/M, lgtm, cncf-cla: yes
